import { RADIUS, SPACE, TYPO } from "@/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  content: { gap: SPACE.md, paddingBottom: SPACE.xxl },
  detail: { gap: SPACE.md, paddingBottom: SPACE.md },
  detailHeader: { alignItems: "center", flexDirection: "row", gap: SPACE.sm, justifyContent: "space-between" },
  detailMeta: { ...TYPO.caption },
  detailNet: { ...TYPO.metric },
  earning: { flex: 1, gap: 2 },
  earningLabel: { ...TYPO.metricLabel },
  earningValue: { ...TYPO.metric, fontSize: 24, lineHeight: 28 },
  earningsRow: { flexDirection: "row", gap: SPACE.md },
  fill: { flex: 1 },
  grow: { flex: 1, minWidth: 0 },
  lineItem: {
    alignItems: "center",
    flexDirection: "row",
    gap: SPACE.sm,
    justifyContent: "space-between",
    paddingHorizontal: SPACE.md,
    paddingVertical: SPACE.sm,
  },
  lineItemAmount: { ...TYPO.captionStrong },
  lineItemText: { ...TYPO.caption, flex: 1 },
  lineItems: { borderRadius: RADIUS.md, borderWidth: 1, overflow: "hidden" },
  nextNote: { ...TYPO.caption },
  privacy: {
    alignItems: "flex-start",
    borderRadius: RADIUS.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: SPACE.sm,
    padding: SPACE.md,
  },
  privacyText: { ...TYPO.caption, flex: 1 },
  quickAction: {
    alignItems: "center",
    borderRadius: RADIUS.pill,
    borderWidth: 1,
    flexDirection: "row",
    gap: SPACE.xxs,
    paddingHorizontal: SPACE.sm,
    paddingVertical: SPACE.xxs,
  },
  quickActionText: { ...TYPO.subtitle },
  quickActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACE.xs,
    paddingBottom: SPACE.sm,
    paddingLeft: 56,
    paddingRight: SPACE.md,
  },
  railHandle: { ...TYPO.caption, marginTop: 2 },
  railMain: {
    alignItems: "center",
    flexDirection: "row",
    gap: SPACE.md,
    minHeight: 72,
    paddingHorizontal: SPACE.md,
  },
  railRow: { gap: 0 },
  railTitle: { ...TYPO.rowTitle },
  railTitleRow: { alignItems: "center", flexDirection: "row", gap: SPACE.xs },
  toast: {
    alignItems: "center",
    alignSelf: "center",
    borderRadius: RADIUS.pill,
    borderWidth: 1,
    bottom: 40,
    flexDirection: "row",
    gap: SPACE.xs,
    paddingHorizontal: SPACE.md,
    paddingVertical: SPACE.sm,
    position: "absolute",
  },
  toastText: { ...TYPO.caption },
  totalLabel: { ...TYPO.caption },
  totalRow: { flexDirection: "row", justifyContent: "space-between" },
  totalValue: { ...TYPO.caption },
  totalValueBold: { ...TYPO.rowTitle },
  totalsBlock: { gap: SPACE.xs },
});
