/**
 * Front Range candidate pool for Denver-batch-1.
 *
 * Each entry is a real Colorado business across the 4 target verticals.
 * Compiled from training knowledge; MX validation + scraping happens at
 * import time so any stale entries are dropped.
 *
 * Coverage:
 *   - Restaurants & food service (~30): mix of Denver / Boulder / FoCo /
 *     Springs independents and small chains. Many refrigerated.
 *   - Big-box retail + grocery + DC operators (~15): Front Range
 *     grocers and specialty food shops. Most refrigerated.
 *   - Freight brokers + 3PLs (~15): regional carriers and Denver
 *     terminals of national fleets.
 *   - Construction supply (~20): plumbing, HVAC, lumber, equipment
 *     rental, building-material wholesalers.
 *
 * Tier hint: A=enterprise/national, B=multi-location regional,
 * C=single-location SMB.
 */

export type FrontRangeCandidate = {
  companyName: string;
  /** Bare domain — no protocol, no path. */
  domain: string;
  industry:
    | "restaurants"
    | "bigbox"
    | "brokers"
    | "smallbiz"
    | "construction";
  city: string;
  state: "CO" | "WY";
  tierHint: "A" | "B" | "C";
  refrigerated: boolean;
  /** Operator-facing note explaining the angle. */
  notes: string;
};

export const DENVER_BATCH_1: FrontRangeCandidate[] = [
  // ─── Restaurants & food service ─────────────────────────────────
  {
    companyName: "Snooze, an A.M. Eatery",
    domain: "snoozeeatery.com",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "B",
    refrigerated: true,
    notes: "Multi-location breakfast chain HQ at 3001 Brighton Blvd. Refrigerated dairy + egg deliveries daily.",
  },
  {
    companyName: "Illegal Pete's",
    domain: "illegalpetes.com",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "B",
    refrigerated: true,
    notes: "Mexican fast-casual, 10+ Front Range + west-slope locations. Refrigerated protein + dairy.",
  },
  {
    companyName: "Modern Market Eatery",
    domain: "modernmarket.com",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "B",
    refrigerated: true,
    notes: "Healthy fast-casual chain, Denver HQ. Refrigerated produce + protein.",
  },
  {
    companyName: "Sushi Den",
    domain: "sushiden.net",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "Denver Pearl Street institution. Daily refrigerated seafood deliveries.",
  },
  {
    companyName: "Root Down",
    domain: "rootdowndenver.com",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "Edible Beats group — farm-to-table. Refrigerated produce.",
  },
  {
    companyName: "TAG Restaurant",
    domain: "tag-restaurant.com",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "Larimer Square global fare. Refrigerated.",
  },
  {
    companyName: "Frasca Food and Wine",
    domain: "frascafoodandwine.com",
    industry: "restaurants",
    city: "Boulder",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "James Beard winner, Boulder. Refrigerated specialty deliveries.",
  },
  {
    companyName: "The Kitchen Restaurant Group",
    domain: "thekitchenbistros.com",
    industry: "restaurants",
    city: "Boulder",
    state: "CO",
    tierHint: "B",
    refrigerated: true,
    notes: "Multi-location Boulder/Denver. Farm-to-table sourcing.",
  },
  {
    companyName: "Hapa Sushi Grill",
    domain: "hapasushi.com",
    industry: "restaurants",
    city: "Boulder",
    state: "CO",
    tierHint: "B",
    refrigerated: true,
    notes: "Multi-location Boulder/Denver. Refrigerated seafood daily.",
  },
  {
    companyName: "Pizzeria Locale",
    domain: "pizzerialocale.com",
    industry: "restaurants",
    city: "Boulder",
    state: "CO",
    tierHint: "B",
    refrigerated: true,
    notes: "Chipotle-incubated fast-casual pizza. Refrigerated produce + dough.",
  },
  {
    companyName: "Tocabe",
    domain: "tocabe.com",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "Indigenous American food. 2 Denver locations.",
  },
  {
    companyName: "Steuben's Food Service",
    domain: "steubens.com",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "Uptown classic + Aurora. Refrigerated American comfort food.",
  },
  {
    companyName: "WaterCourse Foods",
    domain: "watercoursefoods.com",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: false,
    notes: "All-vegan, Denver. Dry + produce.",
  },
  {
    companyName: "Bonanno Concepts",
    domain: "bonannoconcepts.com",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "B",
    refrigerated: true,
    notes: "Restaurant group — Mizuna, Osteria Marco, Luca, Salt & Grinder, etc.",
  },
  {
    companyName: "Mercantile Dining & Provision",
    domain: "mercantiledenver.com",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "Union Station market + restaurant. Refrigerated daily.",
  },
  {
    companyName: "Stoic & Genuine",
    domain: "stoicandgenuine.com",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "Union Station seafood. Daily refrigerated fish.",
  },
  {
    companyName: "Old Major",
    domain: "oldmajordenver.com",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "LoHi farm-to-table. Whole-animal program.",
  },
  {
    companyName: "Acorn at The Source",
    domain: "denveracorn.com",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "RiNo wood-fired. Refrigerated produce.",
  },
  {
    companyName: "Beast + Bottle",
    domain: "beastandbottle.com",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "Uptown farm-to-table. Refrigerated.",
  },
  {
    companyName: "Mizu Izakaya",
    domain: "mizuizakaya.com",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "RiNo izakaya. Refrigerated seafood.",
  },
  {
    companyName: "Coopersmith's Pub & Brewing",
    domain: "coopersmithspub.com",
    industry: "restaurants",
    city: "Fort Collins",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "Fort Collins Old Town anchor since 1989.",
  },
  {
    companyName: "Avanti Food & Beverage",
    domain: "avantifandb.com",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "LoHi + Boulder food hall operators.",
  },
  {
    companyName: "Cuba Cuba Cafe",
    domain: "cubacubacafe.com",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "Multi-location Cuban. Refrigerated.",
  },
  {
    companyName: "Sherpa House",
    domain: "sherpahouse.com",
    industry: "restaurants",
    city: "Golden",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "Golden + multi-location Nepali. Refrigerated.",
  },
  {
    companyName: "Yellowbelly Chicken",
    domain: "yellowbellychicken.com",
    industry: "restaurants",
    city: "Boulder",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "Boulder rotisserie. Refrigerated protein.",
  },
  {
    companyName: "Edible Beats",
    domain: "ediblebeats.com",
    industry: "restaurants",
    city: "Denver",
    state: "CO",
    tierHint: "B",
    refrigerated: true,
    notes: "Root Down parent group: Linger, Ophelia's, El Five.",
  },

  // ─── Big-box retail + grocery + DCs ─────────────────────────────
  {
    companyName: "Natural Grocers by Vitamin Cottage",
    domain: "naturalgrocers.com",
    industry: "bigbox",
    city: "Lakewood",
    state: "CO",
    tierHint: "A",
    refrigerated: true,
    notes: "HQ Lakewood, ~165 stores across 21 states. Refrigerated DC ops.",
  },
  {
    companyName: "King Soopers (Kroger)",
    domain: "kingsoopers.com",
    industry: "bigbox",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: true,
    notes: "Kroger subsidiary. Denver DC, refrigerated.",
  },
  {
    companyName: "Tony's Market",
    domain: "tonysmarkets.com",
    industry: "bigbox",
    city: "Denver",
    state: "CO",
    tierHint: "B",
    refrigerated: true,
    notes: "Denver gourmet butcher + grocer, 3 locations.",
  },
  {
    companyName: "Marczyk Fine Foods",
    domain: "marczykfinefoods.com",
    industry: "bigbox",
    city: "Denver",
    state: "CO",
    tierHint: "B",
    refrigerated: true,
    notes: "Denver specialty grocer, 2 locations.",
  },
  {
    companyName: "Leevers Locavore",
    domain: "leeverslocavore.com",
    industry: "bigbox",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "Highlands neighborhood grocer.",
  },
  {
    companyName: "Polidori Sausage",
    domain: "polidorisausage.com",
    industry: "bigbox",
    city: "Denver",
    state: "CO",
    tierHint: "B",
    refrigerated: true,
    notes: "Family-run Italian sausage maker since 1925. Refrigerated.",
  },
  {
    companyName: "Stranahan's Colorado Whiskey",
    domain: "stranahans.com",
    industry: "bigbox",
    city: "Denver",
    state: "CO",
    tierHint: "B",
    refrigerated: false,
    notes: "Denver distillery, national distribution.",
  },
  {
    companyName: "Haystack Mountain Cheese",
    domain: "haystackmountaincheese.com",
    industry: "bigbox",
    city: "Boulder",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "Boulder goat cheese maker.",
  },
  {
    companyName: "MouCo Cheese Company",
    domain: "mouco.com",
    industry: "bigbox",
    city: "Fort Collins",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "Fort Collins artisan cheese.",
  },
  {
    companyName: "Spinelli's Italian Market",
    domain: "spinellismarket.com",
    industry: "bigbox",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "Park Hill Italian market + deli.",
  },
  {
    companyName: "Continental Sausage",
    domain: "continentalsausage.com",
    industry: "bigbox",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "German sausage maker, Denver. Refrigerated.",
  },
  {
    companyName: "Shamrock Foods Company",
    domain: "shamrockfoodservice.com",
    industry: "bigbox",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: true,
    notes: "Major regional foodservice distributor. Denver DC.",
  },
  {
    companyName: "Cured Boulder",
    domain: "curedboulder.com",
    industry: "bigbox",
    city: "Boulder",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "Boulder cheese + charcuterie shop.",
  },
  {
    companyName: "Tender Belly",
    domain: "tenderbelly.com",
    industry: "bigbox",
    city: "Denver",
    state: "CO",
    tierHint: "B",
    refrigerated: true,
    notes: "Denver premium pork brand.",
  },
  {
    companyName: "Tony Rigatoni's",
    domain: "tonyrigatonis.com",
    industry: "bigbox",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: true,
    notes: "Italian deli + restaurant.",
  },

  // ─── Freight brokers + 3PLs ─────────────────────────────────────
  {
    companyName: "Western Distributing",
    domain: "westerndistributing.com",
    industry: "brokers",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: true,
    notes: "Major Colorado beverage distributor + logistics.",
  },
  {
    companyName: "Estes Express Lines (Denver)",
    domain: "estes-express.com",
    industry: "brokers",
    city: "Commerce City",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "National LTL, Denver terminal.",
  },
  {
    companyName: "Old Dominion Freight Line (Denver)",
    domain: "odfl.com",
    industry: "brokers",
    city: "Commerce City",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "LTL national, Denver terminal.",
  },
  {
    companyName: "Saia LTL Freight (Denver)",
    domain: "saia.com",
    industry: "brokers",
    city: "Aurora",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "LTL national, Denver terminal.",
  },
  {
    companyName: "ABF Freight (Denver)",
    domain: "abf.com",
    industry: "brokers",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "LTL national, Denver terminal.",
  },
  {
    companyName: "XPO Logistics (Denver)",
    domain: "xpo.com",
    industry: "brokers",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "LTL + brokerage, Denver office.",
  },
  {
    companyName: "C.H. Robinson (Denver)",
    domain: "chrobinson.com",
    industry: "brokers",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: true,
    notes: "Largest US freight broker, Denver office.",
  },
  {
    companyName: "Schneider National (Denver)",
    domain: "schneider.com",
    industry: "brokers",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: true,
    notes: "Mega-carrier, Denver ops.",
  },
  {
    companyName: "Coyote Logistics (UPS)",
    domain: "coyote.com",
    industry: "brokers",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: true,
    notes: "UPS brokerage arm, Denver office.",
  },
  {
    companyName: "Landstar System (Denver)",
    domain: "landstar.com",
    industry: "brokers",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "BCO trucking network.",
  },
  {
    companyName: "R&L Carriers (Denver)",
    domain: "rlcarriers.com",
    industry: "brokers",
    city: "Henderson",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "LTL, Denver terminal.",
  },
  {
    companyName: "Penske Logistics (Denver)",
    domain: "penskelogistics.com",
    industry: "brokers",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "Penske 3PL services.",
  },
  {
    companyName: "FedEx Freight (Denver)",
    domain: "fedex.com",
    industry: "brokers",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "Denver LTL terminal.",
  },
  {
    companyName: "YRC Freight / Yellow (Denver)",
    domain: "myyellow.com",
    industry: "brokers",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "LTL.",
  },
  {
    companyName: "Echo Global Logistics",
    domain: "echo.com",
    industry: "brokers",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: true,
    notes: "Brokerage with Denver presence.",
  },

  // ─── Construction supply ────────────────────────────────────────
  {
    companyName: "Ferguson Plumbing Supply (Denver)",
    domain: "ferguson.com",
    industry: "construction",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "National plumbing + HVAC wholesaler, multiple Denver branches.",
  },
  {
    companyName: "HD Supply",
    domain: "hdsupply.com",
    industry: "construction",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "MRO + construction supply, Denver branches.",
  },
  {
    companyName: "Wagner Equipment Co.",
    domain: "wagnerequipment.com",
    industry: "construction",
    city: "Aurora",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "Caterpillar dealer for CO/NM. Aurora HQ.",
  },
  {
    companyName: "United Rentals (Denver)",
    domain: "unitedrentals.com",
    industry: "construction",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "Largest US equipment rental, Denver locations.",
  },
  {
    companyName: "Sunstate Equipment Co.",
    domain: "sunstateequip.com",
    industry: "construction",
    city: "Denver",
    state: "CO",
    tierHint: "B",
    refrigerated: false,
    notes: "Equipment rental, Denver branches.",
  },
  {
    companyName: "White Cap Construction Supply",
    domain: "whitecap.com",
    industry: "construction",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "Specialty contractor supply, multiple Denver branches.",
  },
  {
    companyName: "ABC Supply Co.",
    domain: "abcsupply.com",
    industry: "construction",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "Roofing + siding wholesaler.",
  },
  {
    companyName: "Boise Cascade Building Materials",
    domain: "bc.com",
    industry: "construction",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "Wholesale lumber + building products distribution.",
  },
  {
    companyName: "84 Lumber (Denver)",
    domain: "84lumber.com",
    industry: "construction",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "Pro builder lumber yard.",
  },
  {
    companyName: "Foxworth-Galbraith Lumber",
    domain: "fglumber.com",
    industry: "construction",
    city: "Denver",
    state: "CO",
    tierHint: "B",
    refrigerated: false,
    notes: "Regional lumber + building materials.",
  },
  {
    companyName: "R.E. Michel Company",
    domain: "remichel.com",
    industry: "construction",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "HVAC parts wholesaler, Denver branches.",
  },
  {
    companyName: "Active Plumbing Supply",
    domain: "activeplumbingsupply.com",
    industry: "construction",
    city: "Denver",
    state: "CO",
    tierHint: "C",
    refrigerated: false,
    notes: "Denver independent plumbing wholesale.",
  },
  {
    companyName: "Eaton Metal Products",
    domain: "eatonmetal.com",
    industry: "construction",
    city: "Denver",
    state: "CO",
    tierHint: "B",
    refrigerated: false,
    notes: "Steel tank + fabrication, Denver.",
  },
  {
    companyName: "SiteOne Landscape Supply",
    domain: "siteone.com",
    industry: "construction",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "Largest US landscape supplier.",
  },
  {
    companyName: "Builders FirstSource (Denver)",
    domain: "bldr.com",
    industry: "construction",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: false,
    notes: "Largest US building products supplier.",
  },
  {
    companyName: "Pro Group, Inc.",
    domain: "progroupinc.com",
    industry: "construction",
    city: "Denver",
    state: "CO",
    tierHint: "B",
    refrigerated: false,
    notes: "Building envelope + insulation distributor.",
  },
  {
    companyName: "Bock Lighting (Denver)",
    domain: "bocklighting.com",
    industry: "construction",
    city: "Denver",
    state: "CO",
    tierHint: "B",
    refrigerated: false,
    notes: "Commercial lighting supply.",
  },
  {
    companyName: "Schenker Logistics (Denver)",
    domain: "dbschenkerusa.com",
    industry: "brokers",
    city: "Denver",
    state: "CO",
    tierHint: "A",
    refrigerated: true,
    notes: "DB Schenker 3PL.",
  },
  {
    companyName: "Hercules Industries",
    domain: "herculesindustries.com",
    industry: "construction",
    city: "Denver",
    state: "CO",
    tierHint: "B",
    refrigerated: false,
    notes: "HVAC + sheet metal Denver-headquartered distributor.",
  },
  {
    companyName: "Aurora Industries (Denver)",
    domain: "auroraindustriesinc.com",
    industry: "construction",
    city: "Aurora",
    state: "CO",
    tierHint: "C",
    refrigerated: false,
    notes: "Local plumbing + heating wholesaler.",
  },
];
