import { StyleSheet } from "react-native";
import { SPACE, TYPO } from "@/theme";
export const styles = StyleSheet.create({
  actionButton: { flex: 1 },
  actionRow: { flexDirection: "row", gap: SPACE.sm },
  blockedNote: { ...TYPO.subtitle, lineHeight: 16 },
  content: { gap: SPACE.md, paddingBottom: SPACE.xxl },
  detailImage: { height: "100%", width: "100%" },
  detailImageFallback: { alignItems: "center", flex: 1, gap: SPACE.xs, justifyContent: "center" },
  detailImageFallbackLabel: { ...TYPO.subtitle },
  detailImageFrame: { borderTopLeftRadius: 16, borderTopRightRadius: 16, height: 190, overflow: "hidden" },
  driverMeta: { ...TYPO.caption, marginTop: 2 },
  driverName: { ...TYPO.rowTitle },
  driverRow: { alignItems: "center", flexDirection: "row", gap: SPACE.md },
  emptyNote: { ...TYPO.body },
  error: { ...TYPO.subtitle, paddingBottom: SPACE.md, paddingHorizontal: SPACE.lg },
  expiry: { ...TYPO.subtitle, maxWidth: 120, textAlign: "right" },
  fill: { flex: 1 },
  grow: { flex: 1, minWidth: 0 },
  headRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  odometer: { ...TYPO.metric, fontSize: 22, lineHeight: 26 },
  serviceRow: {
    alignItems: "center",
    borderTopWidth: 1,
    flexDirection: "row",
    gap: SPACE.xs,
    paddingTop: SPACE.sm,
  },
  serviceText: { ...TYPO.caption, flex: 1 },
  sheetBody: { paddingBottom: SPACE.md },
  sheetSectionLabel: { ...TYPO.captionStrong, marginBottom: SPACE.xs, marginTop: SPACE.md },
  thumbnailControls: { alignItems: "center", flexDirection: "row", gap: SPACE.md, padding: SPACE.md },
  thumbnailMeta: { ...TYPO.subtitle, marginTop: 2 },
  thumbnailTitle: { ...TYPO.rowTitle },
  transferSummary: { borderRadius: 12, gap: SPACE.xxs, padding: SPACE.md },
  transferSummaryLabel: { ...TYPO.caption },
  transferSummaryValue: { ...TYPO.body, marginBottom: SPACE.xs },
  unassigned: { ...TYPO.body },
});
