import { StyleSheet } from "react-native";

import { FONTS, RADIUS, SPACING, THEME } from "@/theme";

/** The full-screen new job composer: nav bar, field rows, pills and the customer search. */
export const newJobFormStyles = StyleSheet.create({
  newJobModal: {
    flex: 1,
    backgroundColor: THEME.background,
  },
  newJobNav: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: SPACING.xl,
    paddingVertical: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
  },
  newJobNavCancel: {
    fontFamily: FONTS.medium,
    fontSize: 16,
    color: THEME.primary,
  },
  newJobNavTitle: {
    fontFamily: FONTS.bold,
    fontSize: 17,
    color: THEME.text,
  },
  newJobNavNext: {
    fontFamily: FONTS.semibold,
    fontSize: 16,
    color: THEME.primary,
  },
  newJobScroll: {
    flex: 1,
    paddingTop: SPACING.lg,
  },
  newJobError: {
    marginHorizontal: SPACING.lg,
    marginBottom: SPACING.md,
    padding: SPACING.md,
    backgroundColor: `rgba(239,68,68,0.12)`,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: `rgba(239,68,68,0.3)`,
  },
  newJobErrorText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#FF3B30",
  },
  newJobCard: {
    marginHorizontal: SPACING.lg,
    marginBottom: SPACING.md,
    backgroundColor: THEME.surface,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: THEME.border,
    overflow: "hidden",
  },
  newJobRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: SPACING.lg,
    paddingVertical: 14,
    minHeight: 52,
  },
  newJobRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
  },
  newJobRowLabel: {
    fontFamily: FONTS.medium,
    fontSize: 15,
    color: THEME.text,
    flex: 1,
  },
  newJobRowValue: {
    fontFamily: FONTS.regular,
    fontSize: 15,
    color: THEME.textSecondary,
  },
  newJobPillRow: {
    flexDirection: "row",
    gap: 6,
  },
  newJobPill: {
    backgroundColor: THEME.surfaceElevated,
    borderRadius: RADIUS.sm,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  newJobPillText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: THEME.text,
  },
  newJobPillSelected: {
    backgroundColor: `${THEME.primary}15`,
    borderColor: THEME.primary,
  },
  newJobUnschedule: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: THEME.primary,
    paddingVertical: 4,
  },
  newJobSelectPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: THEME.surfaceElevated,
    borderRadius: RADIUS.sm,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  newJobSelectPillText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: THEME.text,
  },
  newJobArrivalDesc: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: THEME.textMuted,
    marginTop: 4,
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.sm,
  },
  newJobCustomerSearch: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
  },
  newJobCustomerSearchInput: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 14,
    color: THEME.text,
    paddingVertical: 4,
  },
  newJobDropdown: {
    paddingHorizontal: SPACING.sm,
    paddingBottom: SPACING.sm,
  },
  newJobDropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.sm,
  },
  newJobDropdownText: {
    fontFamily: FONTS.medium,
    fontSize: 14,
    color: THEME.text,
    flex: 1,
  },
  newJobCustomerChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: `${THEME.primary}12`,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
    maxWidth: 200,
  },
  newJobCustomerChipText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: THEME.text,
    flex: 1,
  },
});
