import {
  buildVariableMap,
  renderTemplate,
  type RenderContext,
  type RenderLead,
  type RenderSettings,
} from "./render";
import { rewriteLinks } from "@/lib/tracking/links";
import { pixelHtml } from "@/lib/tracking/pixel";
import { buildFooter, unsubscribeHeaders } from "@/lib/compliance/footer";

/**
 * Compose pipeline output. The Gmail provider (next step) wraps this in MIME
 * multipart/alternative + headers and posts it to gmail.users.{drafts,messages}.
 */
export type ComposedEmail = {
  subject: string;
  html: string;
  text: string;
  headers: {
    "List-Unsubscribe": string;
    "List-Unsubscribe-Post": string;
  };
  meta: {
    used: string[];
    unknown: string[];
    rewrittenLinkCount: number;
    skippedLinkCount: number;
  };
};

export type ComposeInputs = {
  /** Generated by the caller before composing — used for both the open pixel and click rewrites. */
  eventId: string;
  /** The lead being emailed; required for unsubscribe-token binding and footer. */
  lead: RenderLead & { id: string };
  /** Subject line template (variables OK). */
  subject: string;
  /** HTML body template (variables OK). */
  bodyHtml: string;
  /** Plain-text body template; if omitted, derived from bodyHtml by stripping tags. */
  bodyText?: string;
  settings: RenderSettings & {
    businessAddress: string;
    businessMc?: string | null;
    businessUsdot?: string | null;
  };
  context?: RenderContext;
};

const TAG_STRIP_RE = /<\/?[a-zA-Z][^>]*>/g;
const WHITESPACE_RE = / | /g;

function htmlToPlainText(html: string): string {
  return html
    .replace(/<br\s*\/?>(?!\s*<\/)/gi, "\n")
    .replace(/<\/p>\s*<p[^>]*>/gi, "\n\n")
    .replace(/<\/li>\s*<li[^>]*>/gi, "\n• ")
    .replace(/<li[^>]*>/gi, "• ")
    .replace(TAG_STRIP_RE, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(WHITESPACE_RE, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

export function composeEmail(input: ComposeInputs): ComposedEmail {
  const variables = buildVariableMap(input.lead, input.settings, input.context);

  const subjectRender = renderTemplate(input.subject, variables);
  const htmlRender = renderTemplate(input.bodyHtml, variables);
  const textSource = input.bodyText ?? htmlToPlainText(input.bodyHtml);
  const textRender = renderTemplate(textSource, variables);

  // Click tracking on rendered HTML (so any URL the template renders gets wrapped).
  const linkResult = rewriteLinks(htmlRender.output, input.eventId);

  // Footer in both formats — uses the lead's id for the unsubscribe token.
  const footer = buildFooter({
    leadId: input.lead.id,
    businessName: input.settings.businessName,
    businessAddress: input.settings.businessAddress,
    businessMc: input.settings.businessMc,
    businessUsdot: input.settings.businessUsdot,
  });

  // Open pixel goes after the footer so it's the very last thing in the body.
  const finalHtml = `${linkResult.html}\n${footer.html}\n${pixelHtml(input.eventId)}`;
  const finalText = `${textRender.output}\n${footer.text}`;

  const headers = unsubscribeHeaders(input.lead.id, input.settings.senderEmail);

  return {
    subject: subjectRender.output,
    html: finalHtml,
    text: finalText,
    headers: {
      "List-Unsubscribe": headers.listUnsubscribe,
      "List-Unsubscribe-Post": headers.listUnsubscribePost,
    },
    meta: {
      used: dedupe([
        ...subjectRender.used,
        ...htmlRender.used,
        ...textRender.used,
      ]),
      unknown: dedupe([
        ...subjectRender.unknown,
        ...htmlRender.unknown,
        ...textRender.unknown,
      ]),
      rewrittenLinkCount: linkResult.rewrittenCount,
      skippedLinkCount: linkResult.skippedCount,
    },
  };
}

function dedupe<T>(arr: T[]): T[] {
  return [...new Set(arr)];
}
