import { StyleSheet } from "react-native";

import { FONTS, RADIUS_LEGACY as RADIUS, SPACING, THEME } from "@/theme";
import { HOUR_HEIGHT } from "./utils";

/**
 * Ported verbatim from the Appliance Diagnostic Systems schedule at
 * 480991b7eb0036e4e85c37d3784b2de2ca97d10d so the two schedules share one
 * geometry. Only the token import changes: MF exposes the same reference
 * palette through `@/theme` rather than `@/constants/theme`.
 *
 * Appliance-specific style names are kept (`cardApplianceStack`,
 * `dayBlockApplianceImage`) because they are the reference's names; the
 * freight screens fill them with equipment artwork instead.
 */

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: THEME.background,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  headerBtn: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: `${THEME.primary}15`,
  },
  headerAddBtn: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: `${THEME.primary}15`,
  },
  floatingTodayWrap: {
    position: "absolute",
    bottom: 90,
    alignSelf: "center",
    zIndex: 50,
  },
  floatingTodayBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 24,
    backgroundColor: THEME.primary,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 8,
  },
  floatingTodayText: {
    fontFamily: FONTS.semibold,
    fontSize: 14,
    color: "#FFF",
  },
  calendarStrip: {
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
    paddingVertical: SPACING.sm,
  },
  calendarScroll: {
    paddingHorizontal: SPACING.sm,
    gap: 2,
  },
  calendarDay: {
    alignItems: "center",
    width: 44,
    paddingVertical: SPACING.xs,
  },
  calendarDaySelected: {},
  calendarDayLabel: {
    fontFamily: FONTS.medium,
    fontSize: 11,
    color: THEME.textMuted,
    marginBottom: 4,
  },
  calendarDayLabelSelected: {
    color: THEME.text,
  },
  calendarDayNum: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarDayNumSelected: {
    backgroundColor: THEME.primary,
  },
  calendarDayNumToday: {
    borderWidth: 2,
    borderColor: THEME.primary,
  },
  calendarDayNumText: {
    fontFamily: FONTS.semibold,
    fontSize: 15,
    color: THEME.textSecondary,
  },
  calendarDayNumTextSelected: {
    color: "#FFF",
  },
  calendarDayNumTextToday: {
    color: THEME.primary,
  },
  calendarDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: THEME.primary,
    marginTop: 3,
  },
  techFilterRow: {
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.xs,
    paddingBottom: 2,
  },
  viewToggle: {
    flexDirection: "row",
    marginHorizontal: SPACING.lg,
    marginTop: SPACING.xs,
    marginBottom: SPACING.xs,
    backgroundColor: THEME.surface,
    borderRadius: RADIUS.md,
    padding: 3,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  viewToggleBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 8,
    borderRadius: RADIUS.sm,
  },
  viewToggleBtnActive: {
    backgroundColor: `${THEME.primary}20`,
  },
  viewToggleText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: THEME.textMuted,
  },
  viewToggleTextActive: {
    color: THEME.text,
    fontFamily: FONTS.semibold,
  },
  loadingWrap: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  listScroll: {
    flex: 1,
    paddingHorizontal: SPACING.lg,
  },
  emptyListWrap: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 80,
    gap: 12,
  },
  emptyListTitle: {
    fontFamily: FONTS.bold,
    fontSize: 17,
    color: THEME.text,
  },
  emptyListSub: {
    fontFamily: FONTS.regular,
    fontSize: 14,
    color: THEME.textMuted,
    textAlign: "center",
  },
  dateSection: {
    marginTop: SPACING.md,
  },
  dateSectionHeader: {
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
    marginBottom: SPACING.sm,
  },
  dateSectionHeaderToday: {
    borderBottomColor: THEME.primary,
  },
  dateSectionTitle: {
    fontFamily: FONTS.semibold,
    fontSize: 14,
    color: THEME.textSecondary,
  },
  dateSectionTitleToday: {
    color: THEME.primary,
    fontFamily: FONTS.bold,
  },
  appointmentCard: {
    flexDirection: "row",
    backgroundColor: THEME.surface,
    borderRadius: RADIUS.lg,
    padding: SPACING.md,
    marginBottom: SPACING.sm,
    borderWidth: 1,
    borderColor: THEME.border,
    alignItems: "stretch",
    overflow: "hidden",
    minHeight: 130,
  },
  pastCard: {
    opacity: 0.6,
  },
  appointmentTimeCol: {
    width: 52,
    marginRight: SPACING.sm,
    justifyContent: "flex-start",
  },
  appointmentTime: {
    fontFamily: FONTS.semibold,
    fontSize: 12,
    color: THEME.text,
  },
  appointmentDuration: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: THEME.textMuted,
    marginTop: 2,
  },
  appointmentColorBar: {
    width: 3,
    borderRadius: 2,
    alignSelf: "stretch",
    marginRight: SPACING.sm,
  },
  appointmentDetails: {
    flex: 1,
  },
  visitLabel: {
    fontFamily: FONTS.semibold,
    fontSize: 10,
    color: THEME.primary,
    marginBottom: 2,
    letterSpacing: 0.3,
  },
  appointmentTitle: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: THEME.textSecondary,
    marginBottom: 2,
  },
  appointmentCustomer: {
    fontFamily: FONTS.semibold,
    fontSize: 15,
    color: "#FFFFFF",
    marginBottom: 3,
  },
  appointmentAddress: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: THEME.textMuted,
    marginBottom: 2,
  },
  appointmentArrival: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: THEME.textSecondary,
    marginBottom: 4,
  },
  appointmentChevron: {
    marginLeft: SPACING.xs,
    alignSelf: "center",
  },
  partOrderBadge: {
    position: "absolute",
    top: 6,
    left: 6,
    backgroundColor: "#EF4444",
    borderRadius: 10,
    width: 18,
    height: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  cardApplianceStack: {
    position: "absolute",
    bottom: 6,
    left: 10,
    alignItems: "center",
    gap: 3,
  },
  cardBrandFallback: {
    width: 18,
    height: 18,
    borderRadius: 5,
    backgroundColor: "rgba(255,255,255,0.06)",
    alignItems: "center",
    justifyContent: "center",
  },
  cardApplianceImage: {
    width: 36,
    height: 36,
    borderRadius: 8,
  },
  pastText: {
    color: THEME.textMuted,
  },
  techRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  techAvatarStack: {
    flexDirection: "row",
  },
  techAvatarWrap: {},
  techName: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: THEME.textSecondary,
    flex: 1,
  },
  dayViewContainer: {
    flexDirection: "row",
    paddingTop: SPACING.sm,
  },
  timeGutter: {
    width: 52,
    paddingLeft: SPACING.sm,
  },
  hourRow: {
    height: HOUR_HEIGHT,
    justifyContent: "flex-start",
    paddingTop: 2,
  },
  hourLabel: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: THEME.textMuted,
  },
  dayGrid: {
    flex: 1,
    position: "relative",
    marginRight: SPACING.md,
  },
  hourGridRow: {
    height: HOUR_HEIGHT,
    justifyContent: "flex-start",
  },
  hourGridLine: {
    height: 1,
    backgroundColor: THEME.border,
    marginTop: 1,
  },
  nowLine: {
    position: "absolute",
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    zIndex: 10,
  },
  nowDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#EF4444",
    marginLeft: -4,
  },
  nowLineBar: {
    flex: 1,
    height: 2,
    backgroundColor: "#EF4444",
  },
  dayViewBlock: {
    position: "absolute",
    borderRadius: 6,
    padding: 4,
    overflow: "hidden",
  },
  dayViewVisitLabel: {
    fontFamily: FONTS.semibold,
    fontSize: 9,
    color: "rgba(255,255,255,0.85)",
    letterSpacing: 0.3,
    marginBottom: 1,
  },
  dayViewBlockTitle: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: "#FFF",
  },
  dayViewBlockAddr: {
    fontFamily: FONTS.regular,
    fontSize: 10,
    color: "rgba(255,255,255,0.8)",
  },
  dayViewBlockDesc: {
    fontFamily: FONTS.regular,
    fontSize: 10,
    color: "rgba(255,255,255,0.7)",
  },
  dayBlockTechRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    marginTop: 2,
  },
  dayBlockTechChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  dayBlockTechName: {
    fontFamily: FONTS.regular,
    fontSize: 9,
    color: "rgba(255,255,255,0.9)",
  },
  dayBlockApplianceStack: {
    position: "absolute",
    bottom: 4,
    left: 4,
    alignItems: "center",
    gap: 2,
  },
  dayBlockBrandFallback: {
    width: 14,
    height: 14,
    borderRadius: 4,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  dayBlockApplianceImage: {
    width: 28,
    height: 28,
    borderRadius: 6,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: THEME.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: SPACING.xl,
    maxHeight: "85%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: SPACING.xl,
  },
  modalTitle: {
    fontFamily: FONTS.bold,
    fontSize: 18,
    color: THEME.text,
  },
  filterSectionLabel: {
    fontFamily: FONTS.semibold,
    fontSize: 12,
    color: THEME.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: SPACING.sm,
  },
  filterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
  },
  filterRowText: {
    fontFamily: FONTS.medium,
    fontSize: 15,
    color: THEME.text,
    flex: 1,
  },
  filterRowTextActive: {
    color: THEME.primary,
    fontFamily: FONTS.semibold,
  },
  filterCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: THEME.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  filterCheckboxBlack: {
    borderColor: THEME.text,
  },
  filterCheckboxActive: {
    backgroundColor: THEME.primary,
  },
  modalDoneBtn: {
    marginTop: SPACING.xl,
    backgroundColor: THEME.primary,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    alignItems: "center",
  },
  modalDoneBtnText: {
    fontFamily: FONTS.bold,
    fontSize: 15,
    color: "#FFF",
  },
  updateBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: THEME.primary,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  updateBannerText: {
    fontFamily: FONTS.semibold,
    fontSize: 13,
    color: "#fff",
  },
  newJobModal: {
    flex: 1,
    backgroundColor: THEME.background,
  },
  newJobNav: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: SPACING.xl,
    paddingVertical: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
  },
  newJobNavCancel: {
    fontFamily: FONTS.medium,
    fontSize: 16,
    color: THEME.primary,
  },
  newJobNavTitle: {
    fontFamily: FONTS.bold,
    fontSize: 17,
    color: THEME.text,
  },
  newJobNavNext: {
    fontFamily: FONTS.semibold,
    fontSize: 16,
    color: THEME.primary,
  },
  newJobScroll: {
    flex: 1,
    paddingTop: SPACING.lg,
  },
  newJobError: {
    marginHorizontal: SPACING.lg,
    marginBottom: SPACING.md,
    padding: SPACING.md,
    backgroundColor: `rgba(239,68,68,0.12)`,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: `rgba(239,68,68,0.3)`,
  },
  newJobErrorText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#EF4444",
  },
  newJobCard: {
    marginHorizontal: SPACING.lg,
    marginBottom: SPACING.md,
    backgroundColor: THEME.surface,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: THEME.border,
    overflow: "hidden",
  },
  newJobRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: SPACING.lg,
    paddingVertical: 14,
    minHeight: 52,
  },
  newJobRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
  },
  newJobRowLabel: {
    fontFamily: FONTS.medium,
    fontSize: 15,
    color: THEME.text,
    flex: 1,
  },
  newJobRowValue: {
    fontFamily: FONTS.regular,
    fontSize: 15,
    color: THEME.textSecondary,
  },
  newJobPillRow: {
    flexDirection: "row",
    gap: 6,
  },
  newJobPill: {
    backgroundColor: THEME.surfaceElevated,
    borderRadius: RADIUS.md,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  newJobPillText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: THEME.text,
  },
  newJobPillSelected: {
    backgroundColor: `${THEME.primary}15`,
    borderColor: THEME.primary,
  },
  newJobUnschedule: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: THEME.primary,
    paddingVertical: 4,
  },
  newJobSelectPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: THEME.surfaceElevated,
    borderRadius: RADIUS.md,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  newJobSelectPillText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: THEME.text,
  },
  newJobArrivalDesc: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: THEME.textMuted,
    marginTop: 4,
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.sm,
  },
  newJobCustomerSearch: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
  },
  newJobCustomerSearchInput: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 14,
    color: THEME.text,
    paddingVertical: 4,
  },
  newJobDropdown: {
    paddingHorizontal: SPACING.sm,
    paddingBottom: SPACING.sm,
  },
  newJobDropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.md,
  },
  newJobDropdownText: {
    fontFamily: FONTS.medium,
    fontSize: 14,
    color: THEME.text,
    flex: 1,
  },
  newJobCustomerChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: `${THEME.primary}12`,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
    maxWidth: 200,
  },
  newJobCustomerChipText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: THEME.text,
    flex: 1,
  },
  pickerOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  pickerSheet: {
    backgroundColor: THEME.surface,
    borderRadius: 16,
    padding: 20,
    width: "92%",
    maxHeight: "60%",
    marginBottom: 20,
  },
  pickerTitle: {
    fontFamily: FONTS.bold,
    fontSize: 16,
    color: THEME.text,
    marginBottom: 12,
  },
  pickerOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
  },
  pickerOptionText: {
    fontFamily: FONTS.medium,
    fontSize: 15,
    color: THEME.text,
    flex: 1,
  },
  pickerOptionActive: {
    color: THEME.primary,
    fontFamily: FONTS.semibold,
  },
  customerAvatarCircle: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 100,
  },
  customerAvatarText: {
    color: "#FFF",
    fontFamily: FONTS.semibold,
  },
});
