import { FONTS, RADIUS, SPACE, TYPO } from "@/theme";
import {
  StyleSheet
} from "react-native";
import { DAY_WIDTH, DRIVER_LABEL_WIDTH } from './unifiedTypes';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  headerAction: { alignItems: "center", justifyContent: "center", minHeight: 44, minWidth: 44 },
  weekControls: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", paddingHorizontal: SPACE.lg, paddingVertical: SPACE.sm },
  arrowButton: { alignItems: "center", borderRadius: RADIUS.md, height: 44, justifyContent: "center", width: 44 },
  weekLabelButton: { alignItems: "center", flex: 1, gap: 2, minHeight: 44, justifyContent: "center" },
  weekLabel: { ...TYPO.cardTitle, fontFamily: FONTS.bold },
  weekHint: { ...TYPO.captionStrong },
  scheduleContent: { paddingBottom: SPACE.md },
  driverFilterScroll: { flexGrow: 0, flexShrink: 0 },
  driverFilterContent: { alignItems: "center", gap: SPACE.sm, paddingHorizontal: SPACE.lg, paddingBottom: SPACE.sm },
  driverFilter: { alignItems: "center", borderRadius: RADIUS.pill, borderWidth: 1, flexDirection: "row", gap: 6, minHeight: 44, paddingVertical: 8, paddingHorizontal: 12, alignSelf: "flex-start" },
  driverFilterText: { ...TYPO.captionStrong },
  metricsRow: { borderBottomWidth: StyleSheet.hairlineWidth, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: "row", marginBottom: SPACE.sm, marginHorizontal: SPACE.lg },
  metric: { alignItems: "center", flex: 1, paddingVertical: SPACE.sm },
  metricValue: { ...TYPO.heading, fontFamily: FONTS.bold },
  metricLabel: { ...TYPO.caption },
  boardScroll: { paddingHorizontal: SPACE.lg },
  board: { borderRadius: RADIUS.lg, borderWidth: 1, overflow: "hidden" },
  boardHeader: { flexDirection: "row", minHeight: 62 },
  driverLabel: { alignItems: "flex-start", justifyContent: "center", paddingHorizontal: SPACE.sm, width: DRIVER_LABEL_WIDTH },
  driverLabelBody: { flexDirection: "row", gap: SPACE.sm, minHeight: 100 },
  boardEyebrow: { ...TYPO.subtitle, letterSpacing: 1 },
  dayHeader: { alignItems: "center", borderRightWidth: StyleSheet.hairlineWidth, justifyContent: "center", width: DAY_WIDTH },
  dayHeaderLabel: { ...TYPO.subtitle, fontFamily: FONTS.bold, letterSpacing: 1 },
  dayHeaderNumber: { ...TYPO.heading, fontFamily: FONTS.bold, marginTop: 3 },
  driverRow: { flexDirection: "row", minHeight: 100, borderTopWidth: StyleSheet.hairlineWidth },
  driverLabelCopy: { flex: 1, minWidth: 0 },
  driverName: { ...TYPO.captionStrong },
  driverStatus: { ...TYPO.subtitle, marginTop: 2, textTransform: "capitalize" },
  dayCell: { borderRightWidth: StyleSheet.hairlineWidth, gap: 4, justifyContent: "flex-start", padding: 5, width: DAY_WIDTH },
  emptyCell: { alignItems: "center", justifyContent: "center" },
  eventChip: { alignItems: "center", borderRadius: 6, borderWidth: 1, flexDirection: "row", gap: 4, minHeight: 25, paddingHorizontal: 5 },
  eventDot: { borderRadius: 3, height: 6, width: 6 },
  eventText: { ...TYPO.subtitle, flex: 1, fontFamily: FONTS.semibold },
  moreEvents: { ...TYPO.subtitle, paddingLeft: 2 },
  emptyBoard: { alignItems: "center", gap: SPACE.sm, padding: SPACE.xl, width: DRIVER_LABEL_WIDTH + DAY_WIDTH * 7 },
  emptyTitle: { ...TYPO.cardTitle },
  emptyCopy: { ...TYPO.caption, maxWidth: 260, textAlign: "center" },
  legendRow: { alignItems: "center", flexDirection: "row", flexWrap: "wrap", gap: SPACE.md, paddingVertical: SPACE.md },
  legendItem: { alignItems: "center", flexDirection: "row", gap: 5 },
  legendDot: { borderRadius: 4, height: 8, width: 8 },
  legendText: { ...TYPO.caption },
  legendHint: { ...TYPO.caption, marginLeft: "auto" },
  inbox: { borderRadius: RADIUS.lg, borderWidth: 1, marginTop: SPACE.sm, overflow: "hidden" },
  sectionHeading: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", padding: SPACE.md },
  sectionEyebrow: { ...TYPO.subtitle, fontFamily: FONTS.bold, letterSpacing: 1 },
  sectionTitle: { ...TYPO.cardTitle, marginTop: 3 },
  requestRow: { borderTopWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: SPACE.sm, padding: SPACE.md },
  requestCopy: { flex: 1 },
  requestTitle: { ...TYPO.bodyStrong },
  requestMeta: { ...TYPO.caption, marginTop: 3 },
  requestActions: { alignItems: "flex-end", justifyContent: "center" },
  sheetContent: { gap: SPACE.md, paddingBottom: SPACE.md },
  sheetLabel: { ...TYPO.subtitle, fontFamily: FONTS.bold, letterSpacing: 1, marginTop: SPACE.sm },
  sheetDriverRow: { gap: SPACE.sm },
  sheetDriver: { alignItems: "center", borderRadius: RADIUS.md, borderWidth: 1, flexDirection: "row", gap: 6, minHeight: 42, paddingHorizontal: SPACE.sm },
  sheetDriverText: { ...TYPO.captionStrong },
  sheetDate: { ...TYPO.heading, fontFamily: FONTS.bold },
  detailTitleRow: { alignItems: "flex-start", flexDirection: "row", gap: SPACE.sm, justifyContent: "space-between" },
  detailTitle: { ...TYPO.heading, fontFamily: FONTS.bold },
  detailTime: { ...TYPO.bodyStrong, marginTop: 4 },
  detailRow: { borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: SPACE.md, paddingVertical: SPACE.sm },
  detailRowLabel: { ...TYPO.captionStrong, width: 70 },
  detailRowValue: { ...TYPO.caption, flex: 1, textTransform: "capitalize" },
  detailCallout: { alignItems: "flex-start", borderRadius: RADIUS.md, borderWidth: 1, flexDirection: "row", gap: SPACE.sm, padding: SPACE.md },
  detailCalloutText: { ...TYPO.caption, flex: 1 },
  syncBadge: { alignItems: "center", borderRadius: RADIUS.pill, borderWidth: 1, flexDirection: "row", gap: 5, paddingHorizontal: 8, paddingVertical: 5 },
  syncDot: { borderRadius: 4, height: 7, width: 7 },
  syncBadgeText: { ...TYPO.subtitle, fontFamily: FONTS.bold },
  syncDetails: { borderRadius: RADIUS.md, borderWidth: 1, gap: SPACE.sm, padding: SPACE.md },
  syncCopy: { ...TYPO.caption },
  sheetActions: { gap: SPACE.sm, marginTop: SPACE.sm },
  coverageIntro: { ...TYPO.body },
  coverageShift: { borderRadius: RADIUS.md, borderWidth: 1, gap: 3, padding: SPACE.md },
  coverageShiftTitle: { ...TYPO.bodyStrong },
  coverageShiftMeta: { ...TYPO.captionStrong },
  candidateRow: { alignItems: "center", borderRadius: RADIUS.md, borderWidth: 1, flexDirection: "row", gap: SPACE.sm, padding: SPACE.sm },
  candidateCopy: { flex: 1 },
  candidateName: { ...TYPO.bodyStrong },
  candidateMeta: { ...TYPO.caption, marginTop: 2, textTransform: "capitalize" },
  noCandidates: { alignItems: "center", gap: SPACE.sm, paddingVertical: SPACE.lg },
  noCandidateTitle: { ...TYPO.bodyStrong },
  noCandidateCopy: { ...TYPO.caption, textAlign: "center" },
  bottomSpace: { height: 60 },
});
