// Keep screen declarations directly visible to Expo Router’s child parser.
export const protectedScreens = [
  { name: "(tabs)" },
  { name: "mfa" },
  { name: "job-assignment/[id]" },
  { name: "load/[id]" },
  { name: "route-planner/[id]" },
  { name: "proof-of-delivery/[id]", options: { animation: "slide_from_bottom" } },
  { name: "exception/new", options: { animation: "slide_from_bottom" } },
  { name: "exception-diagnosis" },
  { name: "exception-diagnostic" },
  { name: "exception-session/[id]" },
  { name: "exception-signals" },
  { name: "exception-codes/index" },
  { name: "exception-codes/[id]" },
  { name: "edi-codes/[id]" },
  { name: "diagnostics/[id]" },
  { name: "documents/[id]" },
  { name: "operations/index" },
  { name: "customers/index" },
  { name: "customers/[id]" },
  { name: "team/index" },
  { name: "team/[id]" },
  { name: "quotes/index" },
  { name: "quotes/[id]" },
  { name: "invoices/index" },
  { name: "invoices/[id]" },
  { name: "loads/index" },
  { name: "loads/new" },
  { name: "leads/index" },
  { name: "leads/new" },
  { name: "leads/[id]" },
  { name: "payments/index" },
  { name: "payments/[id]" },
  { name: "rate-book/index" },
  { name: "rate-book/[id]" },
  { name: "service-programs/index" },
  { name: "service-programs/[id]" },
  { name: "tags/index" },
  { name: "integration-events/index" },
  { name: "integration-events/[id]" },
  { name: "suppliers/index" },
  { name: "suppliers/[id]" },
  { name: "messages" },
  { name: "edi-audit" },
  { name: "hours-of-service" },
  { name: "location-tracker" },
  { name: "history" },
  { name: "knowledge" },
  { name: "analytics" },
  { name: "configure" },
  { name: "profile-details" },
  { name: "freight-document-viewer" },
  { name: "driver-toolbox" },
  { name: "availability" },
  { name: "trip-history" },
  { name: "driver-payments" },
  { name: "fleet/index" },
  { name: "fleet/[id]" },
  { name: "jobs" },
  { name: "driver-scheduling" },
  { name: "payouts/index" },
  { name: "payouts/[id]" },
  { name: "maintenance/index" },
  { name: "maintenance/[id]" },
  { name: "licensing" },
  { name: "workflow-builder", options: { animation: "slide_from_bottom" } },
] as const;
