/**
 * The pinned upstream reference: the commit under contract and the exact set
 * of routes it shipped. Nothing here may drift without re-pinning the commit.
 */

export const REFERENCE_COMMIT = "480991b7eb0036e4e85c37d3784b2de2ca97d10d" as const;

export const REFERENCE_ROUTES = [
  "/(auth)/callback",
  "/(auth)/login",
  "/(auth)/reset-password",
  "/(tabs)",
  "/(tabs)/appliances",
  "/(tabs)/diagnose",
  "/(tabs)/inventory",
  "/(tabs)/schedule",
  "/(tabs)/service-requests",
  "/(tabs)/settings",
  "/analytics",
  "/configure",
  "/diagnosis",
  "/diagnostic",
  "/encompass-parts",
  "/encompass-parts/cart",
  "/encompass-parts/orders",
  "/encompass-parts/part-detail",
  "/encompass-parts/return-request",
  "/encompass-parts/search",
  "/error-codes",
  "/error-codes/[id]",
  "/hcp",
  "/hcp/customer/[id]",
  "/hcp/customers",
  "/hcp/employees",
  "/hcp/estimates",
  "/hcp/invoices",
  "/hcp/job/[id]",
  "/hcp/job/find-parts",
  "/hcp/jobs",
  "/hcp/leads",
  "/hcp/payments",
  "/hcp/pricebook",
  "/hcp/service-plans",
  "/hcp/tags",
  "/hcp/webhook-events",
  "/history",
  "/knowledge",
  "/marcone-parts",
  "/marcone-parts/cart",
  "/marcone-parts/orders",
  "/marcone-parts/part-detail",
  "/marcone-parts/return-request",
  "/marcone-parts/search",
  "/messages",
  "/models",
  "/models/[id]",
  "/new-diagnosis",
  "/parts",
  "/parts/[id]",
  "/parts/analytics",
  "/parts/canvas",
  "/parts/catalog-scan",
  "/parts/global-search",
  "/parts/orders",
  "/parts/scan",
  "/parts/transfer",
  "/parts/van",
  "/profile-details",
  "/session/[id]",
  "/symptoms",
  "/tech-sheet-viewer",
  "/tools-supplies",
  "/tree-editor",
  "/union-parts",
] as const;

export type ReferenceRoute = (typeof REFERENCE_ROUTES)[number];
