import { StyleSheet } from "react-native";

import { CARD_SHADOW_SM, FONTS, RADIUS_LEGACY as RADIUS, SPACING, THEME } from "@/theme";

export const homeOverviewStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: THEME.background },
  center: { flex: 1, justifyContent: "center", alignItems: "center", paddingHorizontal: SPACING.xxxl },
  scroll: { paddingHorizontal: SPACING.lg, paddingBottom: SPACING.xxxl },
  heroRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: SPACING.md,
    marginBottom: SPACING.xl,
  },
  heroDate: {
    fontFamily: FONTS.semibold,
    fontSize: 12,
    color: THEME.primaryLight,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  greetingText: {
    fontFamily: FONTS.bold,
    fontSize: 26,
    color: THEME.text,
    letterSpacing: -0.3,
  },
  greetingSub: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: THEME.textMuted,
    marginTop: 2,
  },
  heroRight: { alignItems: "center", gap: 4 },
  orbContainer: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  liveIndicator: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: `${THEME.success}30`,
    alignItems: "center",
    justifyContent: "center",
  },
  liveDotInner: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: THEME.success,
  },
  liveText: {
    fontFamily: FONTS.semibold,
    fontSize: 9,
    color: THEME.success,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  statsRow: {
    flexDirection: "row",
    gap: SPACING.sm,
    marginBottom: SPACING.lg,
  },
  statPill: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    backgroundColor: THEME.surface,
    borderRadius: RADIUS.lg,
    padding: SPACING.md,
    borderWidth: 1,
    borderColor: THEME.border,
    ...CARD_SHADOW_SM,
  },
  statDot: {
    width: 32,
    height: 32,
    borderRadius: RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
  },
  statValue: {
    fontFamily: FONTS.bold,
    fontSize: 16,
    color: THEME.text,
  },
  statLabel: {
    fontFamily: FONTS.medium,
    fontSize: 10,
    color: THEME.textMuted,
    marginTop: 1,
  },
  alertBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    backgroundColor: `${THEME.orange}08`,
    borderWidth: 1,
    borderColor: `${THEME.orange}25`,
    borderRadius: RADIUS.lg,
    padding: SPACING.md,
    marginBottom: SPACING.lg,
  },
  alertIconBg: {
    width: 28,
    height: 28,
    borderRadius: RADIUS.sm,
    backgroundColor: `${THEME.orange}18`,
    alignItems: "center",
    justifyContent: "center",
  },
  alertText: {
    flex: 1,
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: THEME.orange,
  },
});
