import { StyleSheet } from "react-native";

import { CARD_SHADOW_SM, FONTS, RADIUS as RADII, RADIUS_LEGACY as RADIUS, SPACE, SPACING, THEME, TYPO as TYPE } from "@/theme";

export const homeAdminStyles = StyleSheet.create({
  scroll: {
    paddingHorizontal: SPACE.lg,
    paddingTop: SPACE.md,
    paddingBottom: SPACE.xl,
    gap: SPACE.md,
  },
  headerRow: { flexDirection: "row", alignItems: "flex-start", gap: SPACE.md },
  headerCopy: { flex: 1, gap: 2 },
  headerSubtitle: { ...TYPE.caption, color: THEME.textSecondary, marginTop: -2 },
  headerAction: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: THEME.surfaceElevated,
    alignItems: "center",
    justifyContent: "center",
  },
  tiles: { flexDirection: "row", flexWrap: "wrap", gap: SPACE.sm },
  attentionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACE.sm,
    paddingVertical: SPACE.xs,
  },
  attentionCopy: { flex: 1, gap: 2 },
  attentionTitle: { ...TYPE.rowTitle, color: THEME.text },
  attentionHint: { ...TYPE.subtitle, color: THEME.textSecondary },
  attentionButton: {
    minHeight: 40,
    paddingHorizontal: SPACE.md,
    borderRadius: RADII.pill,
    borderWidth: 1.5,
    borderColor: THEME.text,
    alignItems: "center",
    justifyContent: "center",
  },
  attentionButtonText: { ...TYPE.captionStrong, color: THEME.text },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
    marginBottom: SPACING.lg,
  },
  statCard: {
    width: "47.5%",
    backgroundColor: THEME.surface,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: THEME.border,
    padding: SPACING.md,
    alignItems: "flex-start",
    gap: SPACING.xs,
    ...CARD_SHADOW_SM,
  },
  statIcon: {
    width: 34,
    height: 34,
    borderRadius: RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 2,
  },
  statVal: {
    fontFamily: FONTS.bold,
    fontSize: 22,
    color: THEME.text,
    letterSpacing: -0.5,
  },
  statLbl: {
    fontFamily: FONTS.medium,
    fontSize: 11,
    color: THEME.textMuted,
  },
  techChip: {
    alignItems: "center",
    gap: 6,
    minWidth: 56,
  },
  techChipAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: THEME.surfaceElevated,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 2,
    borderColor: THEME.border,
  },
  techChipInitials: {
    fontFamily: FONTS.bold,
    fontSize: 16,
    color: THEME.textMuted,
  },
  techChipName: {
    fontFamily: FONTS.medium,
    fontSize: 11,
    color: THEME.textSecondary,
    maxWidth: 56,
    textAlign: "center",
  },
});
